### ISSUE TITLE
[docs] Documentação de acesso ao DataLake

### ISSUE THREAD

**Issue by d116626** [prefeitura-rio/pipelines#24]
### Docs para Cidadão

  - indicar como acessar o dado no datario
    - como identificar os dados do datalake?
    - como criar uma conta no GCP (importante lembrar que tem 1TB na faixa)
    - como acessar os dados no console do BQ
  - video passo a passo de como acessar os dados
     - explicar sobre a interface do BQ
     - mostrar schema com descricoes das colunas, detalhes e preview das tabelas
     - explicar sobre a nomeação e padronização dos dados
     - como exportar os dados
     - ver bytes processados, particoes, views
  - entrevistas de usabilidade

### Docs para servidor que quer acessar dados internos

  - pontos focais de cada secretaria
    - conta de acesso ao BQ
  - ver Docs para Cidadão 
  - como conectar o PowerBI 
  - como acessar via Python

### Library

- como deixar o nosso Library publico igual ao do nyt --> https://github.com/nytimes/library

- Estrutura de organização 
  - Tutoriais
    - Acessando dados no BQ
    - Acessando dados no Python, R
    - Conectando no PowerBI
  - Datalake
    - Nomeclatura de bases, visao geral,...
  -  Infraestrutura
     - Pipelines ....,

refs: [tutoriais do google](https://www.youtube.com/watch?v=MH5M2Crn6Ag)

**Comment by fernandascovino** [comment]
- [x] @gabriel-milan criar demo user para acesso aberto ao library - ex: https://nyt-library-demo.herokuapp.com/
- [ ] @fernandascovino @JoaoCarabetta subir base de exemplo da smtr completa (data.rio -> datalake) 🚌
- [ ] @d116626 @patriciacatandi reorganizar library
- [ ] @patriciacatandi escrever tuto de como acessar os dados - ref: https://basedosdados.github.io/mais/access_data_bq/
- [ ] subir bases pra prod antes de gravar os videos @d116626 @fernandascovino 
- [ ] @fernandascovino gravar videos tutoriais

**Comment by gabriel-milan** [comment]
> * [ ]  @gabriel-milan criar demo user para acesso aberto ao library - ex: https://nyt-library-demo.herokuapp.com/

@fernandascovino já havia tentado fazer isso, sem sucesso (vide https://github.com/prefeitura-rio/library-customization/blob/master/userAuth.js). na época, entrei em contato com a equipe do Library, que não soube me dizer o motivo de não funcionar e também pararam de responder.

**Comment by gabriel-milan** [comment]
acompanhar em https://github.com/prefeitura-rio/pipelines/issues/7

**Comment by patriciacatandi** [comment]
Link do drive com os tutoriais prontos:
2 - Como criar uma conta no GCP
3- Acessando dados no BQ
4 - Acessando dados via python 
https://drive.google.com/drive/folders/1nZ0KI6DmtFyJrSCzpldKeHdICEt0MyyZ?usp=sharing
