### ISSUE TITLE
Criar pipeline para o projeto do MIT

### ISSUE THREAD

**Issue by pixuimpou** [prefeitura-rio/pipelines#680]
- [ ] Atualizar o modelo diariamente

**Comment by pixuimpou** [comment]
Reunião essa semana (a principio na quinta-feira) para alinhar o que deve ser feito

**Comment by fernandascovino** [comment]
Ashley vai rodar para uma amostra. Mostramos a ele como usar o dbt local. Ainda não é necessário criar a pipeline, vou fechar o issue por ora.
