### ISSUE TITLE
[docs] Documentação para uso do datalake

### ISSUE THREAD

**Issue by gabriel-milan** [prefeitura-rio/pipelines#7]
Migrado para https://github.com/prefeitura-rio/queries-datario/issues/13

**Comment by fernandascovino** [comment]
**discussão atual:** 

- criamos uma pagina intro no site?
- subimos o docs da hashcorp?
- subimos um mkdocs?
- contratar uma Product Education Engineer such as @yhyakuna - can wee chat any time to talk about great documentation? you rock!

**por que?** 

* tem que estar muito facil e explicativo para quem for sair do evento dia 10/06 ja começar a usar
* colocar essa pagina inicial num qrcode no final da apresentação
* não pode ter uma pagina de atenticacao da google no qrcode (#foralibrary)

- exemplo: https://coronacidades.org/farol-covid-2/

- o que ter na pagina:
  - descrição do **datalake**
  - menu com infos rápidas de: 
    - Onde encontrar os dados no Data.rio
    - [Como acessar o datalake: conta Google (sadbox sem cartao, vide BD)](https://basedosdados.github.io/mais/access_data_bq/)
    - Como acessar via Python/R
    - Como acessar via PowerBI

- sonho de princesa (vault docs): https://github.com/hashicorp/vault/tree/e53aeddd56487a260283cda7cfbf37c96d439cf6/website#editing-navigation-sidebars
